# Docker image for ComfyUI

image::https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-regular.yml/badge.svg["GitHub Workflow Status"]

image::docs/chart-concept.zh.svg["布局"]

用于
https://github.com/comfyanonymous/ComfyUI[ComfyUI]
的
https://hub.docker.com/r/yanwk/comfyui-boot[Docker 镜像] 。

ComfyUI 是一个使用节点工作流的 Stable Diffusion 图形界面。


## 工作流程

1. 初次启动时，启动脚本会下载 ComfyUI、必要的模型以及一些扩展。
2. 整个 ComfyUI 会保存在本地 (`./storage/ComfyUI`) 。
3. 如果你已经有了现成的 ComfyUI 包，放在上述目录，并新建一个空白文件 (`./storage/.download-complete`)，启动脚本会跳过下载。
4. 使用 ComfyUI-Manager 即可更新组件、安装模型（在 ComfyUI 页面中找到“Manager”）。


## 运行前提

* NVIDIA 显卡， ≥6GB 显存
** 4GB 方法见 <<q-n-a, Q & A>>
** AMD 显卡见 <<rocm, ROCm>>

* 安装好最新的 NVIDIA 显卡驱动
** 游戏驱动或 Studio 驱动均可。
** 只需要在宿主系统中安装驱动即可，容器中不需要再安装驱动。

* 安装好 Docker
** Linux 用户可能需要安装 https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html[NVIDIA Container Toolkit] （使得容器可以访问宿主机的 GPU）。
** Windows 用户建议使用 https://www.docker.com/products/docker-desktop/[Docker Desktop] 并在安装时启用 WSL2，并 https://zhuanlan.zhihu.com/p/345645621[限制内存用量] 。
** 下载过程可能需要科学上网，在 Docker 设置中可以找到代理设置。


## 运行方法 - NVIDIA 显卡

.方法 A 使用 `docker compose`
[source,sh]
----
git clone https://github.com/YanWenKun/ComfyUI-Docker.git

cd ComfyUI-Docker

docker compose up --detach

# 更新镜像（仅在 Python 组件版本过期时需要）
git pull
docker compose pull
docker compose up --detach --remove-orphans
docker image prune
----

.方法 B 使用 `docker run`
[source,sh]
----
mkdir -p storage

docker run -it \
  --name comfyui \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="" \
  yanwk/comfyui-boot:latest

# 更新镜像（仅在 Python 组件版本过期时需要）
docker rm comfyui
docker pull yanwk/comfyui-boot:latest
# 接下来再运行一遍上述 'docker run' 即可
----

启动完成后，访问 http://localhost:8188/


[[rocm]]
## 运行方法 - AMD 显卡（尚在实验）

NOTE: AMD/Intel GPU + Win11 可以考虑： *link:docs/wsl-directml.zh.adoc[在 WSL2 环境下通过 DirectML 运行 ComfyUI]*

.方法 C 使用 `docker compose`
[source,sh]
----
git clone https://github.com/YanWenKun/ComfyUI-Docker.git

cd ComfyUI-Docker

docker compose -f docker-compose-rocm.yml up --detach

# 更新镜像（仅在 Python 组件版本过期时需要）
git pull
docker compose -f docker-compose-rocm.yml pull
docker compose -f docker-compose-rocm.yml up --detach --remove-orphans
docker image prune
----

.方法 D 使用 `docker run`
[source,sh]
----
mkdir -p storage

docker run -it \
  --name comfyui \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="--use-pytorch-cross-attention" \
  --device=/dev/kfd --device=/dev/dri \
  --group-add=video --ipc=host --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  yanwk/comfyui-boot:rocm

# 更新镜像（仅在 Python 组件版本过期时需要）
docker rm comfyui
docker pull yanwk/comfyui-boot:rocm
# 接下来再运行一遍上述 'docker run' 即可
----

启动完成后，访问 http://localhost:8188/


[[q-n-a]]
## Q & A

Q: 显存只有 4G 怎么办？ +
A: 在启动参数 `CLI_ARGS` 中添加 `--lowvram` 。

Q: 用了 `--lowvram` 还是显存不够 +
A: 参数换成 `--novram` （直接用 CPU 内存）。

Q: 能不能直接用 CPU 来跑？ +
A: 在启动参数 `CLI_ARGS` 中添加 `--cpu` ，会很慢。

更多 `CLI_ARGS` 参考 
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/cli_args.py[ComfyUI] 。


## 一些方便 Debug 的命令

.构建镜像，打印所有日志（不折叠）
[source,sh]
----
docker build . --progress=plain -f Dockerfile -t yanwk/comfyui-boot:latest
----

.运行一个一次性容器
[source,sh]
----
docker run -it --rm \
  --gpus all -p 8188:8188 \
  --volume "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="" \
  yanwk/comfyui-boot:latest
----

.用 root 身份运行 bash
[source,sh]
----
docker run -it --rm \
  --gpus all -p 8188:8188 \
  --volume "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="" \
  --user root \
  yanwk/comfyui-boot:latest /bin/bash
----


### 使用 Podman 运行

Podman 默认是 root-less 的，不需要 sudo，这也 
https://www.tutorialworks.com/podman-rootless-volumes/[给挂载目录带来了限制] 
。Podman 默认挂载文件为 root 身份，而想要挂载为容器内非 root 用户，
https://docs.podman.io/en/latest/markdown/podman-run.1.html#mount-type-type-type-specific-option[Podman 提供的选项]
则会把主机上的文件给 chown 掉，变成和容器内一样的 uid 和 gid，这可算不上好操作。

这里推荐两种方式绕过：

#### 1. 像 Docker 一样 "root-ful"

.展开细节
[%collapsible]
====
简单直接的方式，用 "sudo" 来运行 Podman 就是 rootful 了，剩下的基本和 Docker 一样，就是记得后续操作也要用 "sudo"。

[source,sh]
----
sudo podman run -it --rm \
  --name comfyui-rootful \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot
----
====

#### 2. 在容器内改为 root 运行

.展开细节
[%collapsible]
====
保持 rootless 风格，容器内文件挂载为 root，程序也以 root 执行。而在主机一侧看来，文件还是本来的用户所有权，也不需要 sudo。

.初次创建脚本 run.sh
[source,sh]
----
tee storage/run.sh >/dev/null <<'EOF'
#!/bin/bash
set -e
ln -sf  /root  /home/runner
cd /root
if [ ! -f "/root/bin/activate" ] ; then
    python3 -m venv --system-site-packages .
fi ;
source /root/bin/activate
chmod +x /home/scripts/entrypoint.sh
source /home/scripts/entrypoint.sh
EOF
----

.运行启动
[source,sh]
----
podman run -it --rm \
  --name comfyui-rootless \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  --user root \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot /bin/bash /root/run.sh
----
====


### 一些自定义节点

.安装一大堆节点，也许能帮你节省点时间
[%collapsible]
====
[source,sh]
----
cd ComfyUI/custom_nodes/

gcs='git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules'

$gcs https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet.git
$gcs https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved.git
$gcs https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git
$gcs https://github.com/FizzleDorf/ComfyUI_FizzNodes.git
$gcs https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID.git
$gcs https://github.com/Fannovel16/comfyui_controlnet_aux.git
$gcs https://github.com/ltdrdata/ComfyUI-Impact-Pack.git
$gcs https://github.com/ltdrdata/ComfyUI-Inspire-Pack.git
$gcs https://github.com/shiimizu/ComfyUI_smZNodes.git
$gcs https://github.com/crystian/ComfyUI-Crystools.git
$gcs https://github.com/jags111/efficiency-nodes-comfyui.git
$gcs https://github.com/cubiq/ComfyUI_essentials.git
$gcs https://github.com/chrisgoringe/cg-use-everywhere.git
$gcs https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git
$gcs https://github.com/pythongosssss/ComfyUI-WD14-Tagger.git
$gcs https://github.com/bash-j/mikey_nodes.git
$gcs https://github.com/twri/sdxl_prompt_styler.git
$gcs https://github.com/rgthree/rgthree-comfy.git
$gcs https://github.com/Fannovel16/ComfyUI-Frame-Interpolation.git
$gcs https://github.com/cubiq/ComfyUI_IPAdapter_plus.git
$gcs https://github.com/SLAPaper/ComfyUI-Image-Selector.git
----
====


### 预启动脚本

如果需要在 ComfyUI 启动前执行脚本，可以创建这个文件：
----
./storage/scripts/pre-start.sh
----


## 声明

代码使用
link:LICENSE[木兰公共许可证, 第2版] 。
中英双语哦！
