# Docker image for ComfyUI

image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-latest.yml/badge.svg["GitHub Workflow Status"]
image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-rocm.yml/badge.svg["GitHub Workflow Status"]
image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-dev.yml/badge.svg["GitHub Workflow Status"]

image::docs/chart-concept.svg["Concept Design"]

*link:README.zh.adoc[>> 中文文档 <<]*

This repo is for 
https://hub.docker.com/r/yanwk/comfyui-boot[Docker images] 
that runs 
https://github.com/comfyanonymous/ComfyUI[ComfyUI] - 
a Stable Diffusion GUI powering node-based workflow.


## How it works

1. At first start, a script will download latest ComfyUI, some custom nodes and models.
2. The whole ComfyUI will be stored in a local folder (`./storage/ComfyUI`).
3. If you already have a ComfyUI bundle, put it there and make an empty file (`./storage/.download-complete`) so the start script will skip downloading.
4. You can update ComfyUI & its custom nodes via ComfyUI-Manager (in ComfyUI web page).


## Prerequisites

* NVIDIA GPU with ≥6GB VRAM
** For 4GB see <<q-n-a, Q & A>>.
** For AMD GPU see <<rocm, ROCm>>.

* Latest NVIDIA GPU driver
** Either Game or Studio edition will work.
** You don't need to install drivers inside containers. Just make sure it's working on your host OS.

* Docker Installed
** Linux user may need to install https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html[NVIDIA Container Toolkit] (only on host OS). It will enable containers' GPU access.
** Windows user could use https://www.docker.com/products/docker-desktop/[Docker Desktop] with WSL2 enabled.


## Usage - NVIDIA GPU

.A. Using `docker compose`
[source,sh]
----
git clone https://github.com/YanWenKun/ComfyUI-Docker.git

cd ComfyUI-Docker

docker compose up --detach

# Update image (only when Python components are outdated)
git pull
docker compose pull
docker compose up --detach --remove-orphans
docker image prune
----

.B. Using `docker run`
[source,sh]
----
mkdir -p storage

docker run -it \
  --name comfyui \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="" \
  yanwk/comfyui-boot:latest

# Update image (only when Python components are outdated)
docker rm comfyui
docker pull yanwk/comfyui-boot:latest
# Then re-run 'docker run' above again
----

Once the app is loaded, visit http://localhost:8188/


[[rocm]]
## Usage - AMD GPU (Experimental)

NOTE: If you are using WSL2 with AMD/Intel GPU, consider *link:docs/wsl-directml.adoc[Run ComfyUI on WSL2 with DirectML]*

.C. Using `docker compose`
[source,sh]
----
git clone https://github.com/YanWenKun/ComfyUI-Docker.git

cd ComfyUI-Docker

docker compose -f docker-compose-rocm.yml up --detach

# Update image (only when Python components are outdated)
git pull
docker compose -f docker-compose-rocm.yml pull
docker compose -f docker-compose-rocm.yml up --detach --remove-orphans
docker image prune
----

.D. Using `docker run`
[source,sh]
----
mkdir -p storage

docker run -it \
  --name comfyui \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="--use-pytorch-cross-attention" \
  --device=/dev/kfd --device=/dev/dri \
  --group-add=video --ipc=host --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  yanwk/comfyui-boot:rocm

# Update image (only when Python components are outdated)
docker rm comfyui
docker pull yanwk/comfyui-boot:rocm
# Then re-run 'docker run' above again
----

Once the app is loaded, visit http://localhost:8188/


[[q-n-a]]
## Q & A

Q: My GPU has only 4GB VRAM +
A: Add `--lowvram` to `CLI_ARGS`.

Q: Adding `--lowvram` still out-of-memory +
A: Use `--novram` instead. It will use CPU RAM.

Q: How to run on CPU? +
A: Add `--cpu` to `CLI_ARGS`. It's pretty slow.

Q: I don't want to use xFormers, how to use PyTorch's Cross Attention? +
A: Add `--use-pytorch-cross-attention` to `CLI_ARGS`. It may perform well on WSL2, but significantly slower on Linux hosts.

More `CLI_ARGS` available at 
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/cli_args.py[ComfyUI].


## Some commands for debugging

.Build the image, print all logs to STDOUT
[source,sh]
----
docker build . --progress=plain -f Dockerfile -t yanwk/comfyui-boot:latest
----

.Run a one-time container
[source,sh]
----
docker run -it --rm \
  --gpus all -p 8188:8188 \
  --volume "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="" \
  yanwk/comfyui-boot:latest
----

.Run into a root bash
[source,sh]
----
docker run -it --rm \
  --gpus all -p 8188:8188 \
  --volume "$(pwd)"/storage:/home/runner \
  --env CLI_ARGS="" \
  --user root \
  yanwk/comfyui-boot:latest /bin/bash
----

### Run with Podman

Podman is root-less by default. And https://www.tutorialworks.com/podman-rootless-volumes/[it's tricky] to bind-mount volume as non-root user inside rootless container. 
https://docs.podman.io/en/latest/markdown/podman-run.1.html#mount-type-type-type-specific-option[Options] provided by Podman will chown files on host space, which probably is undesirable.

I recommend two different ways to workaround:

#### 1. Go "root-ful" just like Docker

.Expand details
[%collapsible]
====
The straightforward way. By adding `sudo` you go from rootless to rootful. And everything else would be the same as using Docker. +
Note that Podman will download images to root, not current user.

[source,sh]
----
sudo podman run -it --rm \
  --name comfyui-rootful \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/home/runner \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot
----
====

#### 2. Run as root inside container

.Expand details
[%collapsible]
====
The rootless way, no sudo needed. Inside the pod, Podman will mount volume as root, scripts will run as root. And from the host side, we see files keep their original ownership.

.Create run.sh
[source,sh]
----
tee ./storage/run.sh >/dev/null <<'EOF'
#!/bin/bash
set -e
ln -sf  /root/.*  /home/runner
ln -sf  /root/*  /home/runner
cd /root
if [ ! -f "/root/bin/python3.11" ] ; then
    python3 -m venv --system-site-packages .
fi ;
source /root/bin/activate
chmod +x /home/scripts/entrypoint.sh
source /home/scripts/entrypoint.sh
EOF
----

.Run
[source,sh]
----
podman run -it --rm \
  --name comfyui-rootless \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  --user root \
  --workdir /root \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:latest \
  /bin/bash /root/run.sh
----
====


### Some custom nodes

.Install a bunch of custom nodes that may save you some time
[%collapsible]
====
Note that most dependencies are bundled in the image, you don't need to manually install them. +
(Except https://pypi.org/project/imageio-ffmpeg/[imageio-ffmpeg]
which uses FFmpeg4. The image came with FFmpeg6 or newer.)

[source,sh]
----
cd ComfyUI/custom_nodes/

gcs='git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules'

$gcs https://github.com/bash-j/mikey_nodes.git
$gcs https://github.com/chrisgoringe/cg-use-everywhere.git
$gcs https://github.com/crystian/ComfyUI-Crystools.git
$gcs https://github.com/cubiq/ComfyUI_essentials.git
$gcs https://github.com/cubiq/ComfyUI_IPAdapter_plus.git
$gcs https://github.com/Fannovel16/comfyui_controlnet_aux.git
$gcs https://github.com/Fannovel16/ComfyUI-Frame-Interpolation.git
$gcs https://github.com/FizzleDorf/ComfyUI_FizzNodes.git
$gcs https://github.com/jags111/efficiency-nodes-comfyui.git
$gcs https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet.git
$gcs https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved.git
$gcs https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git
$gcs https://github.com/ltdrdata/ComfyUI-Impact-Pack.git
$gcs https://github.com/ltdrdata/ComfyUI-Inspire-Pack.git
$gcs https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git
$gcs https://github.com/pythongosssss/ComfyUI-WD14-Tagger.git
$gcs https://github.com/rgthree/rgthree-comfy.git
$gcs https://github.com/shiimizu/ComfyUI_smZNodes.git
$gcs https://github.com/SLAPaper/ComfyUI-Image-Selector.git
$gcs https://github.com/twri/sdxl_prompt_styler.git
$gcs https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID.git
----

Another note is this image doesn't bundled deps for
https://github.com/WASasquatch/was-node-suite-comfyui[WAS Node Suite],
because it has some deps version
https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/requirements.txt[fixed],
and is not under active development. +
However, the image's script only install one custom node (ComfyUI-Manager). In a new deployment, you can safely install WAS NS via ComfyUI-Manager. If anything conflicts, just delete unwanted custom nodes and `.local` folder, and update/try fix/reinstall custom nodes in ComfyUI-Manager.
====


### Pre-start script

You can create your own pre-start script at
----
./storage/scripts/pre-start.sh
----
It will run before ComfyUI starts, handy for debugging.


## License

link:LICENSE[Mulan Public License，Version 2]

This open source license is written and valid both in Chinese and English, how good is that!
