# Docker Image with Preview (Nightly) Dependencies for ComfyUI

image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-nightly.yml/badge.svg["GitHub Workflow Status",link="https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-nightly.yml"]

https://hub.docker.com/r/yanwk/comfyui-boot/tags?name=nightly[View on <Docker Hub>]

## Note

* This image won't download ComfyUI or any models. Please prepare your ComfyUI suite before running the container.

* Part of the `Dockerfile` is commented out due to CI limitation:

** Only basic dependencies for running ComfyUI is installed. Otherwise the image would be too big that GitHub Actions would throw IOException.

** `xFormers` is not installed in this image.
It requires building from source in order to use it with PyTorch nightly. And building xFormers (with comprehensive build targets) on GitHub Actions would often result in halt (maybe just unpaid version).

** If you build the image by yourself, you can uncomment the lines in `Dockerfile`, for a bigger, yet more comprehensive image.

## Running

* Don't forget to put ComfyUI in the `storage` folder.

.Using Docker
[source,sh]
----
docker pull yanwk/comfyui-boot:nightly

docker run -it --rm \
  --name comfyui-nightly \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -e CLI_ARGS="--fast --preview-method taesd --front-end-version Comfy-Org/ComfyUI_frontend@latest" \
  -e PIP_INDEX_URL="https://pypi.org/simple" \
  -e HF_ENDPOINT="https://huggingface.co" \
  yanwk/comfyui-boot:nightly
----

.Using Podman
[source,sh]
----
podman pull docker.io/yanwk/comfyui-boot:nightly

podman run -it --rm \
  --name comfyui-nightly \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  --security-opt seccomp=unconfined \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -e CLI_ARGS="--fast --preview-method taesd --front-end-version Comfy-Org/ComfyUI_frontend@latest" \
  -e PIP_INDEX_URL="https://pypi.org/simple" \
  -e HF_ENDPOINT="https://huggingface.co" \
  yanwk/comfyui-boot:nightly
----
