# 基于 AMD GPU + ROCm 运行 ComfyUI

中文 | ℹ️ *link:README.adoc[English]*

image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-rocm7.yml/badge.svg["GitHub Workflow Status",link="https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-rocm7.yml"]

https://hub.docker.com/r/yanwk/comfyui-boot/tags?name=rocm7[在 <Docker Hub> 上查看]

TIP: 本镜像使用最新的 ROCm 7，仅推荐给 Radeon RX 9000 系列（RDNA 4）和 Ryzen AI 300 系列（RDNA 3.5）用户。
更早的 GPU 用户推荐使用更稳定的
link:../rocm6/README.zh.adoc[`rocm6`]
镜像。

## 准备工作

* 确保宿主机已安装 AMD GPU 驱动（内核模块 `amdgpu`）。

* 检查你的 GPU/CPU 是否被 ROCm 支持：
** https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html[支持的 GPU 列表]
** https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/compatibility/compatibilityryz/native_linux/native_linux_compatibility.html#gpu-support-matrix[支持的 Ryzen CPU (APU) 列表]

** RX 6000 系列可尝试运行，但不保证功能正常。
*** RX 6000 系列不在 ROCm 7 的官方支持列表中，但 RDNA 2 专业卡（如 W6800）仍被 ROCm 7 支持，它们的编译目标均为 `gfx1030` ，故仍有尝试价值。

* （可选）为防止 `HIP error: an illegal memory access was encountered` 错误，可在宿主机上设置内核参数 `amdgpu.cwsr_enable=0`，具体见
https://github.com/YanWenKun/ComfyUI-Docker/issues/157[issue #157]
（感谢 __SergeyFilippov__ ）。


## 必要环境变量

需根据 GPU 型号添加如下环境变量（感谢
https://github.com/YanWenKun/ComfyUI-Docker/pull/67[nhtua]
的 PR）：

* **RDNA 4** :
** `-e HSA_OVERRIDE_GFX_VERSION=12.0.0 \`
** 参看 https://rocm.docs.amd.com/en/latest/reference/gpu-arch-specs.html[AMD文档] ，部分型号可改用 `12.0.1`

* Ryzen AI **Max** 300 系列 (**RDNA 3.5**):
** `-e HSA_OVERRIDE_GFX_VERSION=11.5.1 \`
** `-e HIP_VISIBLE_DEVICES=0 \`

* Ryzen AI 300 系列 (**RDNA 3.5**):
** `-e HSA_OVERRIDE_GFX_VERSION=11.5.0 \`
** `-e HIP_VISIBLE_DEVICES=0 \`

* **RDNA 3** :
** `-e HSA_OVERRIDE_GFX_VERSION=11.0.0 \`
** 参看 https://rocm.docs.amd.com/en/latest/reference/gpu-arch-specs.html[AMD文档] ，部分型号可改用 `11.0.1`

* **RDNA 2** :
** `-e HSA_OVERRIDE_GFX_VERSION=10.3.0 \`


## 运行

### 使用 Docker

[source,sh]
----
mkdir -p \
#  storage \
  storage-models/models \
  storage-models/hf-hub \
  storage-models/torch-hub \
  storage-user/input \
  storage-user/output \
  storage-user/workflows

docker run \
  --name comfyui-rocm7 \
  --device=/dev/kfd --device=/dev/dri \
  --group-add=video --group-add=render \
  --ipc=host --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  --security-opt label=disable \
  -p 8188:8188 \
#  -v "$(pwd)"/storage:/root \
  -v "$(pwd)"/storage-models/models:/root/ComfyUI/models \
  -v "$(pwd)"/storage-models/hf-hub:/root/.cache/huggingface/hub \
  -v "$(pwd)"/storage-models/torch-hub:/root/.cache/torch/hub \
  -v "$(pwd)"/storage-user/input:/root/ComfyUI/input \
  -v "$(pwd)"/storage-user/output:/root/ComfyUI/output \
  -v "$(pwd)"/storage-user/workflows:/root/ComfyUI/user/default/workflows \
  -e HSA_OVERRIDE_GFX_VERSION="" \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:rocm7
----

### 使用 Podman

[source,sh]
----
mkdir -p \
#  storage \
  storage-models/models \
  storage-models/hf-hub \
  storage-models/torch-hub \
  storage-user/input \
  storage-user/output \
  storage-user/workflows

podman run \
  --name comfyui-rocm7 \
  --device=/dev/kfd --device=/dev/dri \
  --group-add=video --group-add=render \
  --ipc=host --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  --security-opt label=disable \
  -p 8188:8188 \
#  -v "$(pwd)"/storage:/root \
  -v "$(pwd)"/storage-models/models:/root/ComfyUI/models \
  -v "$(pwd)"/storage-models/hf-hub:/root/.cache/huggingface/hub \
  -v "$(pwd)"/storage-models/torch-hub:/root/.cache/torch/hub \
  -v "$(pwd)"/storage-user/input:/root/ComfyUI/input \
  -v "$(pwd)"/storage-user/output:/root/ComfyUI/output \
  -v "$(pwd)"/storage-user/workflows:/root/ComfyUI/user/default/workflows \
  -e HSA_OVERRIDE_GFX_VERSION="" \
  -e CLI_ARGS="" \
  docker.io/yanwk/comfyui-boot:rocm7
----

启动完成后，访问 http://localhost:8188/


## 可选环境变量

注意以下调优均有一定代价，按需使用：

* 强制 ComfyUI 更频繁地将模型权重从显存卸载到内存：

** `-e CLI_ARGS="--disable-smart-memory" \`

** 有效减少显存泄漏，代价是更慢、占用更多系统内存（
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/cli_args.py[源码]
）

* 禁用显存碎片缓存机制：

** `-e HSA_DISABLE_FRAGMENT_ALLOCATOR=1 \`

** 缓解部分显存访问失败的问题，代价是更慢、占用更多显存（
https://rocm.docs.amd.com/projects/ROCR-Runtime/en/latest/api-reference/environment_variables.html[文档] ；
感谢
https://github.com/YanWenKun/ComfyUI-Docker/issues/134[SergeyFilippov]
的 Issue）

* 启用可调优操作（操作自调优）：

** `-e PYTORCH_TUNABLEOP_ENABLED=1 \`

** 首次运行较慢，但之后运行更快（
https://github.com/ROCm/pytorch/tree/main/aten/src/ATen/cuda/tunable[文档1] ，
https://github.com/Comfy-Org/docs/blob/main/troubleshooting/overview.mdx#amd-gpu-issues[文档2] ；
感谢
https://github.com/YanWenKun/ComfyUI-Docker/pull/114[SergeyFilippov]
的 PR）
