# MEGAPAK image for ComfyUI

**__Using PyTorch 2.11 and CUDA 13.0__**

image::concept.svg["Concept Design"]

image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-cu130-megapak-pt211.yml/badge.svg["GitHub Workflow Status",link="https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-cu130-megapak-pt211.yml"]

https://hub.docker.com/r/yanwk/comfyui-boot/tags?name=cu130-megapak-pt211[View on <Docker Hub>]


**MEGAPAK** uses the same base mechanism as the `slim` images. The key differences are:

* Includes 40+ Custom Nodes. See link:../base-cu130-pt211-cache/builder-scripts/preload-cache.sh[the full list].
* Includes CUDA development kit for compiling PyTorch C++ extensions, `.cu` files, etc.
* Includes performance optimization libraries such as Nunchaku and SageAttention (powerful but may have compatibility issues).
* Includes additional tools and dependencies.

Particular to this `cu130-megapak-pt211` image:

* PyTorch 2.11 + CUDA 13.0.

* Pre-installed:
** SageAttention 2
** SageAttention 3
** SpargeAttention
** FlashAttention 2
** FlashAttention 3
** FlashAttention 4
** Nunchaku
** llama-cpp-python
** FastVideo

* With:
** Python 3.13 (with GIL)
** GCC 14
** glibc 2.39 (from Rocky Linux 10)


## Usage

Please successfully run the `slim` image before attempting the `megapak` image. The prerequisites/setup sections are omitted from this document.

### Run with Docker

[source,sh]
----
mkdir -p \
  storage-cache/dot-cache \
  storage-cache/dot-config \
  storage-nodes/dot-local \
  storage-nodes/custom_nodes \
  storage-models/models \
  storage-models/hf-hub \
  storage-models/torch-hub \
  storage-user/input \
  storage-user/output \
  storage-user/user-profile \
  storage-user/user-scripts

docker run -it --rm \
  --name comfyui-megapak \
  --pull=always \
  --runtime=nvidia \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage-cache/dot-cache:/root/.cache \
  -v "$(pwd)"/storage-cache/dot-config:/root/.config \
  -v "$(pwd)"/storage-nodes/dot-local:/root/.local \
  -v "$(pwd)"/storage-nodes/custom_nodes:/root/ComfyUI/custom_nodes \
  -v "$(pwd)"/storage-models/models:/root/ComfyUI/models \
  -v "$(pwd)"/storage-models/hf-hub:/root/.cache/huggingface/hub \
  -v "$(pwd)"/storage-models/torch-hub:/root/.cache/torch/hub \
  -v "$(pwd)"/storage-user/input:/root/ComfyUI/input \
  -v "$(pwd)"/storage-user/output:/root/ComfyUI/output \
  -v "$(pwd)"/storage-user/user-profile:/root/ComfyUI/user \
  -v "$(pwd)"/storage-user/user-scripts:/root/user-scripts \
  -e CLI_ARGS="--fast" \
  yanwk/comfyui-boot:cu130-megapak-pt211
----

### Run with Podman (rootless)

[source,bash]
----
mkdir -p \
  storage-cache/dot-cache \
  storage-cache/dot-config \
  storage-nodes/dot-local \
  storage-nodes/custom_nodes \
  storage-models/models \
  storage-models/hf-hub \
  storage-models/torch-hub \
  storage-user/input \
  storage-user/output \
  storage-user/user-profile \
  storage-user/user-scripts

podman run -it --rm \
  --name comfyui-megapak \
  --pull=newer \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage-cache/dot-cache:/root/.cache \
  -v "$(pwd)"/storage-cache/dot-config:/root/.config \
  -v "$(pwd)"/storage-nodes/dot-local:/root/.local \
  -v "$(pwd)"/storage-nodes/custom_nodes:/root/ComfyUI/custom_nodes \
  -v "$(pwd)"/storage-models/models:/root/ComfyUI/models \
  -v "$(pwd)"/storage-models/hf-hub:/root/.cache/huggingface/hub \
  -v "$(pwd)"/storage-models/torch-hub:/root/.cache/torch/hub \
  -v "$(pwd)"/storage-user/input:/root/ComfyUI/input \
  -v "$(pwd)"/storage-user/output:/root/ComfyUI/output \
  -v "$(pwd)"/storage-user/user-profile:/root/ComfyUI/user \
  -v "$(pwd)"/storage-user/user-scripts:/root/user-scripts \
  -e CLI_ARGS="--fast" \
  docker.io/yanwk/comfyui-boot:cu130-megapak-pt211
----

Once the app is loaded, visit http://localhost:8188/

## Tips

* Custom Nodes are copied to local storage at first start, allowing you to install additional Custom Nodes and persist them without conflicts.

** The downside is that you need to update the Custom Nodes via ComfyUI-Manager rather than by pulling new images.

** If you do not need to install additional Custom Nodes and prefer to update by pulling new images, you can remove the bind mounts for `storage-nodes`.

[[cli-args]]
## CLI_ARGS - Attention Selection

[%autowidth,cols=2]
|===
|args |description

|--use-sage-attention
|Use SageAttention 2. Keep current config for xFormers.

|--use-flash-attention
|Use FlashAttention 2. Keep current config for xFormers.

|--use-pytorch-cross-attention
|Use PyTorch's built-in cross-attention. Disable xFormers.

|===

* Only one attention implementation can be selected at a time.
If none is specified, xFormers is enabled by default.

* For example, you may want to use one of these combinations:
** `--use-flash-attention`
** `--use-flash-attention --disable-xformers`
** `--use-sage-attention`
** `--use-sage-attention --disable-xformers`
** `--use-pytorch-cross-attention`
** Leave empty (will use xFormers by default).

### Compatibility (only applies to this image)

[cols="1,1,1,1,1,1", options="header"]
|===
| GPU Architecture
| Blackwell | Hopper | Ada Lovelace | Ampere | Turing

| Example GPU
| RTX 5090 | H100 | RTX 4090 | RTX 3090 
| RTX 2080 +
GTX 1660

| SageAttention 2
| ✔️ | ❓ | ✔️ | ✔️ | ❌

| SageAttention 3
| ✔️ | ❌ | ❌ | ❌ | ❌

| SpargeAttention
| ❌ | ❌ | ✔️ | ✔️ | ❌

| FlashAttention 2
| ✔️ | ✔️ | ✔️ | ✔️ | ❌

| FlashAttention 3
| ✔️ | ✔️ | ❌ | ❌ | ❌

| FlashAttention 4
| ✔️ | ✔️ | ❌ | ❌ | ❌

| xFormers
| ✔️ | ✔️ | ✔️ | ✔️ | ✔️

| PyTorch Native
| ✔️ | ✔️ | ✔️ | ✔️ | ✔️

|===


## CLI_ARGS - Frequently Used

[%autowidth,cols=2]
|===
|args |description

|--disable-xformers
|Disable xFormers.

|--fast
|Enable experimental optimizations.
(e.g. 
https://github.com/Comfy-Org/ComfyUI/commit/9953f22fce0ba899da0676a0b374e5d1f72bf259[float8_e4m3fn] 
matrix multiplication on Ada Lovelace and later GPUs).
Might lower image quality. +
Turn it off if you want stability over speed.

|--disable-smart-memory
|Force ComfyUI to offload models from VRAM to RAM more frequently. Slows performance but reduce memory leaks.

|--lowvram
|Force ComfyUI to split the model (UNET) into parts to use less VRAM, at the cost of speed.

|--novram
|Use system RAM only, no VRAM at all. Very slow.

|--cpu
|Run on CPU. Very slow. Used for testing purposes.

|===

More `CLI_ARGS` available at ComyfyUI's
https://github.com/Comfy-Org/ComfyUI/blob/master/comfy/cli_args.py[cli_args.py].


[[env-vars]]
## Environment Variables Reference

[cols="2,2,3"]
|===
|Variable|Example Value|Memo

|HTTP_PROXY +
HTTPS_PROXY
|http://localhost:1081 +
http://localhost:1081
|Set HTTP proxy. Works the same as in `pre-start.sh`.

|PIP_INDEX_URL
|'https://pypi.org/simple' +
'https://mirrors.cernet.edu.cn/pypi/web/simple'
|Set mirror site of Python Package Index (used by `pip`).

|GITHUB_ENDPOINT
|'https://github.com' +
'https://gh-proxy.org/https://github.com'
|Set mirror site of GitHub (used by ComfyUI-Manager).

|HF_ENDPOINT
|'https://huggingface.co' +
'https://hf-mirror.com'
|Set mirror site of HuggingFace Hub (used by `hf`).

|HF_TOKEN
|'hf_your_token'
|Set HuggingFace Access Token.
https://huggingface.co/settings/tokens[More info]

|HF_XET_HIGH_PERFORMANCE
|1
|Enable HuggingFace Hub's high performance mode.
Only make sense if you have >5Gbps and VERY STABLE connection (e.g. cloud server).
https://huggingface.co/docs/huggingface_hub/main/en/package_reference/environment_variables#hfxethighperformance[More info]

|TORCH_CUDA_ARCH_LIST
|8.6 +
or +
'7.0;7.5;8.0;8.6;9.0;10.0;12.0+PTX'
|Build target for PyTorch and its extensions.
For most users, no setup is needed as it will be automatically selected on Linux.
When needed, you only need to set one build target just for your GPU.
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/[More info]

|CMAKE_ARGS
|'-DBUILD_opencv_world=ON -DWITH_CUDA=ON -DCUDA_FAST_MATH=ON -DWITH_CUBLAS=ON -DWITH_NVCUVID=ON'
|Build options for CMAKE projects using CUDA.

|===
