# Docker Image for ComfyUI-3D-Pack

image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-comfy3d-pt25.yml/badge.svg["GitHub Workflow Status",link="https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-comfy3d-pt25.yml"]

https://hub.docker.com/r/yanwk/comfyui-boot/tags?name=comfy3d-pt25[View on <Docker Hub>]

NOTE: **Currently Not Working on WSL2**.

* By default, install only ComfyUI, AGL Translation, ComfyUI-3D-Pack and custom nodes required by example workflows.
* Will install ComfyUI-Manager, but disable it by default.
* After download complete, will try to rebuild dependencies for 3D-Pack.
** Will target local GPU, usually no need to config. If having issues, try set env var `TORCH_CUDA_ARCH_LIST` and `CMAKE_ARGS` (see table below).
** If rebuild is unnecessary, add an empty file `.build-complete` to the storage folder (just like `.download-complete`).


## Version Info

* ComfyUI-3D-Pack version: latest

* Dev kits:
** CUDA dev kit (12.4)
** Python dev package (3.12)
** GCC C++ (13)

* Key Components:
** torch==2.5.1+cu124
** xformers==0.0.28.post3

Additionally, compiled wheel files for Comfy3D can be found
https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/tag/v5.1[here]
and instructions for compiling can be found
https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/blob/v5.1/README.adoc[here].

## Usage

.Run with Docker
[source,sh]
----
mkdir -p storage

docker run -it --rm \
  --name comfy3d-pt25 \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:comfy3d-pt25
----

.Run with Podman
[source,sh]
----
mkdir -p storage

podman run -it --rm \
  --name comfy3d-pt25 \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -e CLI_ARGS="" \
  docker.io/yanwk/comfyui-boot:comfy3d-pt25
----


include::../docs/section-env-vars.adoc[]
