name: Publish 'comfy3d-pt22' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!comfy3d-pt22/Dockerfile'
      - '!comfy3d-pt22/runner-scripts/**'
      - '!.github/workflows/build-comfy3d-pt22.yml'


jobs:

  build-publish-comfy3d-pt22:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      -
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'comfy3d-pt22'
        uses: docker/build-push-action@v6
        with:
          context: ./comfy3d-pt22
          file: ./comfy3d-pt22/Dockerfile
          tags:  |
            yanwk/comfyui-boot:comfy3d-pt22
            yanwk/comfyui-boot:comfy3d-pt22-${{ steps.date.outputs.date }}
          push: true
