name: Publish 'xpu-test' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!xpu-test/Dockerfile'
      - '!xpu-test/builder-scripts/**'
      - '!xpu-test/runner-scripts/**'
      - '!.github/workflows/build-xpu-test.yml'

jobs:

  build-publish-xpu-test:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 512
      -
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'xpu-test'
        uses: docker/build-push-action@v6
        with:
          context: ./xpu-test
          file: ./xpu-test/Dockerfile
          tags: |
            yanwk/comfyui-boot:xpu-test
            yanwk/comfyui-boot:xpu-test-${{ steps.date.outputs.date }}
          push: true
