name: Publish 'base-cu128-pt27' to Docker Hub

on: 
  workflow_dispatch: # Can only be triggered manually


jobs:

  build-publish-base-cu128-pt27:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      -
        name: Git checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'base-cu128-pt27'
        uses: docker/build-push-action@v6
        with:
          context: ./base-cu128-pt27
          file: ./base-cu128-pt27/Dockerfile
          tags:  |
            yanwk/comfyui-boot:base-cu128-pt27
          push: true
