name: Publish 'cu129-slim' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Monday, 07:00 UTC
    - cron: '0 7 * * 1'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!cu129-slim/Dockerfile'
      - '!cu129-slim/builder-scripts/**'
      - '!cu129-slim/runner-scripts/**'
      - '!.github/workflows/build-cu129-slim.yml'

jobs:

  build-publish-cu129-slim:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 512
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Git checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'cu129-slim'
        uses: docker/build-push-action@v6
        with:
          context: ./cu129-slim
          file: ./cu129-slim/Dockerfile
          tags:  |
            yanwk/comfyui-boot:cu129-slim
            yanwk/comfyui-boot:cu129-slim-${{ steps.date.outputs.date }}
          push: true
