name: Publish 'cu128-test' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Monday, 07:00 UTC
    - cron: '0 7 * * 1'
  push: 
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!cu128-test/Dockerfile'
      - '!cu128-test/builder-scripts/**'
      - '!cu128-test/runner-scripts/**'
      - '!.github/workflows/build-cu128-test.yml'

jobs:

  build-publish-cu128-test:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      -
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'cu128-test'
        uses: docker/build-push-action@v6
        with:
          context: ./cu128-test
          file: ./cu128-test/Dockerfile
          tags:  |
            yanwk/comfyui-boot:cu128-test
            yanwk/comfyui-boot:cu128-test-${{ steps.date.outputs.date }}
          push: true
