# 基于 AMD GPU + ROCm 运行 ComfyUI

中文 | ℹ️ *link:README.adoc[English]*

image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-rocm.yml/badge.svg["GitHub Workflow Status",link="https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-rocm.yml"]

https://hub.docker.com/r/yanwk/comfyui-boot/tags?name=rocm[在 <Docker Hub> 上查看]

## 版本选择

* RDNA 4（Radeon RX 9000 系列）和 RDNA 3.5（Ryzen AI 300 系列）用户需使用 ROCm 7 或未来版本。

* RDNA 3 用户可在 ROCm 7 与 6 之间自由选择，优先选 7。

* RDNA 2 用户推荐使用更稳定的
link:../rocm6/README.zh.adoc[`rocm6`]
镜像。


## 镜像区别

`rocm` 镜像：使用 ROCm 7.2，基于
https://download.pytorch.org/whl/rocm7.2[PyTorch]
发布的二进制包构建，当 PyTorch 发布新版时，`rocm` 可立即得到更新。

`rocm7` 镜像：使用 ROCm 7.2.1，基于 AMD 官方提供的
https://hub.docker.com/r/rocm/pytorch[rocm/pytorch]
镜像构建，该镜像功能更全面，但更新较慢。

如果不清楚如何选择，或者初次接触 ComfyUI，建议用 `rocm` 镜像，遇到兼容性问题再换用 `rocm7` 镜像。


## 准备工作

* 确保宿主机已安装 AMD GPU 驱动（内核模块 `amdgpu`）。

* 检查你的 GPU/CPU 是否被 ROCm 支持：
** https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html[支持的 GPU 列表]
** https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/compatibility/compatibilityryz/native_linux/native_linux_compatibility.html#gpu-support-matrix[支持的 Ryzen CPU (APU) 列表]
** 或参考下表。


## 必要环境变量

需根据 GPU 型号，为容器配置如下环境变量：

[cols="2,3,2", options="header"]
|===
| GPU 架构 | 需配置的环境变量 |  GPU 型号

.4+| RDNA 4 (gfx1201)
.4+| `-e HSA_OVERRIDE_GFX_VERSION=12.0.1 \`
| Radeon AI PRO R9700
| Radeon RX 9070 XT
| Radeon RX 9070
| Radeon RX 9070 GRE

.2+| RDNA 4 (gfx1200)
.2+| `-e HSA_OVERRIDE_GFX_VERSION=12.0.0 \`
| Radeon RX 9060 XT
| Radeon RX 9060

.3+| RDNA 3.5 (gfx1151)
.3+| `-e HSA_OVERRIDE_GFX_VERSION=11.5.1 \` + 
`-e HIP_VISIBLE_DEVICES=0 \`
| Ryzen AI Max+ 395
| Ryzen AI Max 390
| Ryzen AI Max 385

.3+| RDNA 3.5 (gfx1150)
.3+| `-e HSA_OVERRIDE_GFX_VERSION=11.5.0 \` + 
`-e HIP_VISIBLE_DEVICES=0 \`
| Ryzen AI 9 HX 375
| Ryzen AI 9 HX 370
| Ryzen AI 9 365

.4+| RDNA 3 (gfx1101)
.4+| `-e HSA_OVERRIDE_GFX_VERSION=11.0.1 \`
| Radeon PRO W7700
| Radeon PRO V710
| Radeon RX 7800 XT
| Radeon RX 7700 XT

.5+| RDNA 3 (gfx1100)
.5+| `-e HSA_OVERRIDE_GFX_VERSION=11.0.0 \`
| Radeon PRO W7900
| Radeon PRO W7800
| Radeon RX 7900 XTX
| Radeon RX 7900 XT
| Radeon RX 7900 GRE

.2+| RDNA 2 (gfx1030)
.2+| `-e HSA_OVERRIDE_GFX_VERSION=10.3.0 \`
| Radeon PRO W6800
| Radeon PRO V620

|===

* Radeon RX 6000 系列可尝试运行，但不保证功能正常。
** RX 6000 系列不在 ROCm 7 的官方支持列表中，但 RDNA 2 专业卡（如 W6800）仍被 ROCm 7 支持，它们的编译目标均为 `gfx1030` ，故仍有尝试价值。

参考：
https://rocm.docs.amd.com/en/latest/reference/gpu-arch-specs.html[AMD GPU 架构列表]
（感谢
https://github.com/YanWenKun/ComfyUI-Docker/pull/67[nhtua]
的 PR）


## 运行

### 使用 Docker

[source,sh]
----
mkdir -p \
  storage \
  storage-models/models \
  storage-models/hf-hub \
  storage-models/torch-hub \
  storage-user/input \
  storage-user/output \
  storage-user/workflows

docker run -it --rm \
  --name comfyui-rocm \
  --device=/dev/kfd --device=/dev/dri \
  --group-add=video --ipc=host --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -v "$(pwd)"/storage-models/models:/root/ComfyUI/models \
  -v "$(pwd)"/storage-models/hf-hub:/root/.cache/huggingface/hub \
  -v "$(pwd)"/storage-models/torch-hub:/root/.cache/torch/hub \
  -v "$(pwd)"/storage-user/input:/root/ComfyUI/input \
  -v "$(pwd)"/storage-user/output:/root/ComfyUI/output \
  -v "$(pwd)"/storage-user/workflows:/root/ComfyUI/user/default/workflows \
  -e HSA_OVERRIDE_GFX_VERSION="" \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:rocm
----

### 使用 Podman

[source,sh]
----
mkdir -p \
  storage \
  storage-models/models \
  storage-models/hf-hub \
  storage-models/torch-hub \
  storage-user/input \
  storage-user/output \
  storage-user/workflows

podman run -it --rm \
  --name comfyui-rocm \
  --device=/dev/kfd --device=/dev/dri \
  --group-add=video --ipc=host --cap-add=SYS_PTRACE \
  --security-opt seccomp=unconfined \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -v "$(pwd)"/storage-models/models:/root/ComfyUI/models \
  -v "$(pwd)"/storage-models/hf-hub:/root/.cache/huggingface/hub \
  -v "$(pwd)"/storage-models/torch-hub:/root/.cache/torch/hub \
  -v "$(pwd)"/storage-user/input:/root/ComfyUI/input \
  -v "$(pwd)"/storage-user/output:/root/ComfyUI/output \
  -v "$(pwd)"/storage-user/workflows:/root/ComfyUI/user/default/workflows \
  -e HSA_OVERRIDE_GFX_VERSION="" \
  -e CLI_ARGS="" \
  docker.io/yanwk/comfyui-boot:rocm
----

启动完成后，访问 http://localhost:8188/


## 可选环境变量

注意以下调优均有一定代价，按需使用：

* 强制 ComfyUI 更频繁地将模型权重从显存卸载到内存：

** `-e CLI_ARGS="--disable-smart-memory" \`

** 有效减少显存泄漏，代价是更慢、占用更多系统内存（
https://github.com/Comfy-Org/ComfyUI/blob/master/comfy/cli_args.py[源码]
）

* 禁用显存碎片缓存机制：

** `-e HSA_DISABLE_FRAGMENT_ALLOCATOR=1 \`

** 缓解部分显存访问失败的问题，代价是更慢、占用更多显存（
https://rocm.docs.amd.com/projects/ROCR-Runtime/en/latest/api-reference/environment_variables.html[文档] ；
感谢
https://github.com/YanWenKun/ComfyUI-Docker/issues/134[SergeyFilippov]
的 Issue）

* 启用可调优操作（操作自调优）：

** `-e PYTORCH_TUNABLEOP_ENABLED=1 \`

** 首次运行较慢，但之后运行更快（
https://github.com/ROCm/pytorch/tree/main/aten/src/ATen/cuda/tunable[文档1] ，
https://github.com/Comfy-Org/docs/blob/main/troubleshooting/overview.mdx#amd-gpu-issues[文档2] ；
感谢
https://github.com/YanWenKun/ComfyUI-Docker/pull/114[SergeyFilippov]
的 PR）
