# You've found MEGAPAK!

image:https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-cu121-megapak.yml/badge.svg["GitHub Workflow Status",link="https://github.com/YanWenKun/ComfyUI-Docker/actions/workflows/build-cu121-megapak.yml"]

https://hub.docker.com/repository/docker/yanwk/comfyui-boot/tags?name=cu121-megapak[View on <Docker Hub>]


*link:README.zh.adoc[中文说明]*

`megapak` is a big all-in-one Docker image that has:

* Dev kits:
** CUDA dev kit (12.1)
** Python dev package (3.11)
** GCC C++ (12)
** OpenCV-devel
** CMake, Ninja...

* Latest stable version of xFormers + PyTorch

* Tools:
** Vim, Fish, fd...

And will:

* Install a lot of Custom Nodes by default
** Especially https://github.com/MrForExample/ComfyUI-3D-Pack[ComfyUI-3D-Pack] (not easy to install)

* Download more models

Also, if you'd like to build your own development environment for ComfyUI ecosystem, this image would be a good starting point.

## Note - For WSL2 Users

The design of `megapak` is similar to the `latest` image, as well as the usage. With one key difference:

* The user within the container is `root`, not "runner".
** This makes rootless deploy on Linux easier.

But WSL2 users need to be aware of the file storage. +
Bind-mount a directory from Windows(NTFS) filesystem into Linux(ext4) would perform I/O much slower, and have dubious ownership. +
Recommend using a Docker volume or a WSL2 directory for file storage. +
(You can still manage your ComfyUI files in Explorer via URL `\\wsl$`).

More discussion in
https://github.com/YanWenKun/ComfyUI-Docker/issues/43[#43].

`latest` image uses a low-privilege user (runner), so it doesn't have dubious ownership issue under WSL2.

If confused, give a try to the native
https://github.com/YanWenKun/ComfyUI-Windows-Portable[ComfyUI-Windows-Portable].

## Usage

.Run with Docker
[source,sh]
----
mkdir -p storage

docker run -it --rm \
  --name comfyui-mega \
  --gpus all \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -e CLI_ARGS="" \
  yanwk/comfyui-boot:megapak
----

.Run with Podman
[source,sh]
----
mkdir -p storage

podman run -it --rm \
  --name comfyui-mega \
  --device nvidia.com/gpu=all \
  --security-opt label=disable \
  -p 8188:8188 \
  -v "$(pwd)"/storage:/root \
  -e CLI_ARGS="" \
  docker.io/yanwk/comfyui-boot:megapak
----

Recommend running ephemeral containers (`--rm`) to keep everything clean and visible.
